#!/usr/bin/env bash
#
# Run all dotfiles installers.
packagelist="ubuntuPackages"
set -e

cd "$(dirname $0)"/..

if [ "$(uname -s)" == "Darwin" ]
then
  # Run Homebrew through the Brewfile
  echo "› brew bundle"
  brew bundle
elif [ "$(uname -s)" == "Linux" ]
then
  xargs -a <(awk '/^\s*[^#]/' "$packagelist") -r -- sudo apt-get install
fi
# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
